#!/bin/sh
printf "Current afl-qemu-trace architecture: %s\n" \
    "$(basename $(readlink -f /usr/bin/afl-qemu-trace) | cut -d '-' -f4)"

read -p "Choose which architecture to use (aarch64, x86_64, i386): " arch

sudo ln -sf "/usr/bin/afl-qemu-trace-${arch}" /usr/bin/afl-qemu-trace
